export const attendanceMockData = [
  {
    id: 1,
    name: "Semester 1",
    startDate: "31/07/2025",
    endDate: "28/01/2026",
    duration: "182 days",
    overallAttendance: 91,
    totalMarked: 272,
    presentCount: 247,
    absentCount: 25,
    leaveDays: 0,
    internLeaveDays: 0,
    bonusAttendance: 0,
    statusMessage: "Your attendance is good. Keep up the consistent attendance!",
  },
  {
    id: 2,
    name: "Semester 2",
    startDate: "29/01/2026",
    endDate: "30/06/2026",
    duration: "152 days",
    overallAttendance: 93,
    totalMarked: 201,
    presentCount: 187,
    absentCount: 14,
    leaveDays: 0,
    internLeaveDays: 0,
    bonusAttendance: 0,
    statusMessage: "Your attendance is good. Keep up the consistent attendance!",
  },
];
